"""add github_id to users

Revision ID: 0c3113ac0b53
Revises: 49b58b58466a
Create Date: 2026-06-04 04:39:15.985464
"""
from alembic import op
import sqlalchemy as sa


revision = '0c3113ac0b53'
down_revision = '49b58b58466a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
