"""add game_scores table

Revision ID: 0d358dd5a276
Revises: add_category_to_posts
Create Date: 2026-07-04 12:01:35.452052
"""
from alembic import op
import sqlalchemy as sa


revision = '0d358dd5a276'
down_revision = 'add_category_to_posts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_scores_game_name'), 'game_scores', ['game_name'], unique=False)
    op.create_index(op.f('ix_game_scores_id'), 'game_scores', ['id'], unique=False)
    op.create_index(op.f('ix_game_scores_user_id'), 'game_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_scores_user_id'), table_name='game_scores')
    op.drop_index(op.f('ix_game_scores_id'), table_name='game_scores')
    op.drop_index(op.f('ix_game_scores_game_name'), table_name='game_scores')
    op.drop_table('game_scores')
    # ### end Alembic commands ###
