"""add parent_id and reply_to_user_id to comments

Revision ID: 0f1898fbbdd3
Revises: 0c3113ac0b53
Create Date: 2026-06-04 05:47:36.378711
"""
from alembic import op
import sqlalchemy as sa


revision = '0f1898fbbdd3'
down_revision = '0c3113ac0b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('reply_to_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['reply_to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_column('comments', 'reply_to_user_id')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
