"""add_verification_token_expiry

Revision ID: 638e96bfc084
Revises: 98d6a7a0a2af
Create Date: 2026-06-03 18:37:16.766903
"""
from alembic import op
import sqlalchemy as sa


revision = '638e96bfc084'
down_revision = '98d6a7a0a2af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    # ### end Alembic commands ###
