"""add_email_verification

Revision ID: 98d6a7a0a2af
Revises: 20260603_0001
Create Date: 2026-06-03 18:12:01.113029
"""
from alembic import op
import sqlalchemy as sa


revision = '98d6a7a0a2af'
down_revision = '20260603_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('users', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    # ### end Alembic commands ###

    # Set existing users as verified so they can still log in
    op.execute("UPDATE users SET is_verified = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
