"""add tags to posts

Revision ID: af622aba0dcd
Revises: b69ed5cc6c5c
Create Date: 2026-06-03 23:47:41.129034
"""
from alembic import op
import sqlalchemy as sa


revision = 'af622aba0dcd'
down_revision = 'b69ed5cc6c5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
