"""add birthday and gender to users

Revision ID: b69ed5cc6c5c
Revises: 638e96bfc084
Create Date: 2026-06-03 23:03:59.241687
"""
from alembic import op
import sqlalchemy as sa


revision = 'b69ed5cc6c5c'
down_revision = '638e96bfc084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
