"""unify comments with profile_id

Revision ID: bc6e2444e1f6
Revises: fc29ea36cc63
Create Date: 2026-06-04 06:40:37.528973
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bc6e2444e1f6'
down_revision = 'fc29ea36cc63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_comments_author_id', table_name='profile_comments')
    op.drop_index('ix_profile_comments_id', table_name='profile_comments')
    op.drop_index('ix_profile_comments_profile_id', table_name='profile_comments')
    op.drop_table('profile_comments')
    op.add_column('comments', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comments_profile_id'), 'comments', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'users', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_profile_id'), table_name='comments')
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'profile_id')
    op.create_table('profile_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='profile_comments_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['users.id'], name='profile_comments_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profile_comments_pkey')
    )
    op.create_index('ix_profile_comments_profile_id', 'profile_comments', ['profile_id'], unique=False)
    op.create_index('ix_profile_comments_id', 'profile_comments', ['id'], unique=False)
    op.create_index('ix_profile_comments_author_id', 'profile_comments', ['author_id'], unique=False)
    # ### end Alembic commands ###
