"""add reply_preview to comments

Revision ID: df250c6c91ea
Revises: 0f1898fbbdd3
Create Date: 2026-06-04 06:18:25.694072
"""
from alembic import op
import sqlalchemy as sa


revision = 'df250c6c91ea'
down_revision = '0f1898fbbdd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_preview', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_preview')
    # ### end Alembic commands ###
