"""add_links_to_users

Revision ID: ef97d8577267
Revises: bc6e2444e1f6
Create Date: 2026-06-05 08:32:03.414370
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ef97d8577267'
down_revision = 'bc6e2444e1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'links')
    # ### end Alembic commands ###
