"""add profile_comments table

Revision ID: fc29ea36cc63
Revises: df250c6c91ea
Create Date: 2026-06-04 06:31:54.926079
"""
from alembic import op
import sqlalchemy as sa


revision = 'fc29ea36cc63'
down_revision = 'df250c6c91ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_comments_author_id'), 'profile_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_profile_comments_id'), 'profile_comments', ['id'], unique=False)
    op.create_index(op.f('ix_profile_comments_profile_id'), 'profile_comments', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_comments_profile_id'), table_name='profile_comments')
    op.drop_index(op.f('ix_profile_comments_id'), table_name='profile_comments')
    op.drop_index(op.f('ix_profile_comments_author_id'), table_name='profile_comments')
    op.drop_table('profile_comments')
    # ### end Alembic commands ###
